// Generated by `zig build dts`. Do not edit by hand.
// u64/i64 may exceed Number.MAX_SAFE_INTEGER.

export interface ZigCommands {
  sha256: { args: { megabytes: number }; result: { hash: string }; stream: unknown };
  echoBytes: { args: { n: number }; result: Uint8Array; stream: unknown };
  echo: { args: { s: string; fail: boolean }; result: { s: string }; stream: unknown };
}

export declare namespace Zigware {
  function invoke<C extends keyof ZigCommands>(
    name: C, args: ZigCommands[C]["args"],
    opts?: { onStream?: (frame: ZigCommands[C]["stream"]) => void }
  ): Promise<ZigCommands[C]["result"]>;
}
