// Vendored from Zigware; regenerated by `zigware init`. Do not hand-edit.
const std = @import("std");
const protocol = @import("protocol.zig");

/// The shared command State. Mirrors the framework `z.State`; stateless apps
/// ignore `ctx.state`. The real type is unified in the framework build.
pub const State = struct {};

/// Stable machine-readable error crossing the bridge as a structured rejection.
/// `code` and `message` are escaped through `jsString` on the wire (G6 safe for
/// arbitrary bytes). `payload_json` is the ONE field that bypasses `jsString`:
/// it flows through `writeJsonAsJsLiteral`, which trusts its input is already
/// real `std.json` output (M1). CONTRACT: a handler MUST produce `payload_json`
/// with `std.json.Stringify` (never hand-built or raw user bytes); passing raw
/// bytes here is the single way a handler can defeat G6. The Zig side is trusted
/// (security model §2), so this is a documented handler obligation, not an
/// enforced check. Prefer leaving `payload_json` null and putting detail in a
/// typed `Result(T).ok` value, which is always `std.json`-encoded.
pub const CommandError = struct {
    code: []const u8,
    message: []const u8,
    payload_json: ?[]const u8 = null,
};

/// A handler's typed success-or-error return.
pub fn Result(comptime T: type) type {
    return union(enum) { ok: T, err: CommandError };
}

/// Raw bytes that bypass the JSON tax. Routed over the stream scheme, never eval.
pub const Bytes = struct { data: []const u8, mime: []const u8 = "application/octet-stream" };

/// Transparent async marker. Wrapping a return type in Async(...) places the
/// handler on jobs.Pool. The registry unwraps `inner` after the job runs.
pub fn Async(comptime T: type) type {
    return struct { inner: T };
}

/// Helper so an async handler can `return z.done(value);` instead of `.{ .inner = value }`.
pub fn done(value: anytype) Async(@TypeOf(value)) {
    return .{ .inner = value };
}

/// The bridge-owned emit endpoint. Concrete, not type-erased: the bridge fills
/// `evalJS` (closes over the backend + the resolved target label) and
/// `parkBinary` (closes over the per-id ring buffer). All channels and
/// binaryChunk route through here, so there is exactly one call into
/// backend.evalJS (G6). Label-parameterized from the start: `label` names the
/// target window (pre-E always "main"); E generalizes routing without changing
/// this struct's shape.
pub const EmitSink = struct {
    label: []const u8,
    /// Hand a full JS statement (already built via protocol) to the backend for
    /// `label`'s window. Thread-safe (backend.evalJS hops to main). The closure
    /// performs the A-seam alive check before touching backend.evalJS.
    evalJS: *const fn (sink: *EmitSink, js: []const u8) void,
    /// Park raw bytes under (id, seq) for later pull over the scheme path.
    /// Returns false when the per-id binary budget would overflow (G5).
    parkBinary: *const fn (sink: *EmitSink, id: u64, seq: u32, bytes: []const u8) bool,
};

/// Backend-constructed streaming channel keyed by the invoke id. The frontend
/// never constructs one (forgery resistance); it receives frames via opts.onStream.
pub fn Channel(comptime T: type) type {
    return struct {
        const Self = @This();
        emit: *EmitSink,
        id: u64,
        /// The per-call arena (from Ctx). All transient stream buffers allocate
        /// here so they are bounded by the same budget as the rest of the call
        /// and never escape to an untracked global allocator (B4).
        arena: std.mem.Allocator,
        /// Serialize `value` as JSON and emit one ordered _stream frame.
        /// Serialization failure degrades to nothing emitted (the terminal
        /// resolve/reject still settles the promise); never traps.
        pub fn send(self: Self, value: T) void {
            var aw: std.Io.Writer.Allocating = .init(self.arena);
            defer aw.deinit();
            std.json.Stringify.value(value, .{}, &aw.writer) catch return;
            var fw: std.Io.Writer.Allocating = .init(self.arena);
            defer fw.deinit();
            protocol.encodeStream(&fw.writer, self.id, aw.writer.buffered()) catch return;
            self.emit.evalJS(self.emit, fw.writer.buffered());
        }
        /// Emit _streamEnd. The terminal resolve/reject still follows.
        pub fn close(self: Self) void {
            var fw: std.Io.Writer.Allocating = .init(self.arena);
            defer fw.deinit();
            protocol.encodeStreamEnd(&fw.writer, self.id) catch return;
            self.emit.evalJS(self.emit, fw.writer.buffered());
        }
    };
}

/// The per-call context. One per in-flight invoke. The per-call arena is reset
/// (freed) by the bridge after the terminal result is encoded, so handlers
/// allocate freely without manual frees.
pub fn Ctx(comptime State: type) type {
    return struct {
        const Self = @This();

        arena: std.mem.Allocator,
        state: *State,
        id: u64,
        cancel: *std.atomic.Value(bool),
        emit: *EmitSink,
        /// The attested label of the window that made this call. Set by the
        /// bridge per call (defaults to "main" for the pre-E single-window path
        /// and for the existing Ctx literals in tests). G4 scope checks read it.
        window_label: []const u8 = "main",
        /// Type-erased `*Bridge(B)`; the window.* built-ins cast it back to reach
        /// the manager. Null for non-window handlers and pre-E call sites.
        services: ?*anyopaque = null,
        /// Monotonic per-call binary sequence, bumped by binaryChunk.
        bin_seq: u32 = 0,

        pub fn cancelled(self: *Self) bool {
            return self.cancel.load(.acquire);
        }
        pub fn channel(self: *Self, comptime T: type) Channel(T) {
            return .{ .emit = self.emit, .id = self.id, .arena = self.arena };
        }
        /// Park `bytes` and emit a _bin control frame so the frontend pulls them
        /// out-of-band, using the per-call bin_seq (so terminal Bytes and streamed
        /// chunks never collide on a seq, H2). Returns true when the bytes were
        /// parked (regardless of whether the _bin control frame was
        /// emitted: frame emission degrades silently on arena OOM, parallel to
        /// Channel.send, and the parked bytes are reclaimed at call-arena
        /// teardown). Returns false only when the per-id binary budget is exceeded
        /// (nothing parked, no frame).
        pub fn binaryChunk(self: *Self, bytes: []const u8, mime: []const u8) bool {
            const seq = self.bin_seq;
            if (!self.emit.parkBinary(self.emit, self.id, seq, bytes)) return false;
            self.bin_seq += 1;
            var fw: std.Io.Writer.Allocating = .init(self.arena);
            defer fw.deinit();
            protocol.encodeBinReady(&fw.writer, self.id, seq, bytes.len, mime) catch return true;
            self.emit.evalJS(self.emit, fw.writer.buffered());
            return true;
        }
    };
}

// ─── Tests ───────────────────────────────────────────────────────────────────

const Holder = struct {
    sink: EmitSink,
    log: std.ArrayList(u8) = .empty,
    alloc: std.mem.Allocator,

    fn make(alloc: std.mem.Allocator) *Holder {
        const h = alloc.create(Holder) catch unreachable;
        h.* = .{ .alloc = alloc, .sink = .{ .label = "main", .evalJS = evalJS, .parkBinary = parkBinary } };
        return h;
    }
    fn evalJS(sink: *EmitSink, js: []const u8) void {
        const h: *Holder = @fieldParentPtr("sink", sink);
        h.log.appendSlice(h.alloc, js) catch {};
        h.log.append(h.alloc, '\n') catch {};
    }
    fn parkBinary(sink: *EmitSink, _: u64, _: u32, bytes: []const u8) bool {
        const h: *Holder = @fieldParentPtr("sink", sink);
        h.log.appendSlice(h.alloc, bytes) catch {};
        return true;
    }
    fn deinit(h: *Holder) void {
        h.log.deinit(h.alloc);
        const a = h.alloc;
        a.destroy(h);
    }
};

test "Channel.send emits a _stream frame for the bound id" {
    const h = Holder.make(std.testing.allocator);
    defer h.deinit();
    var cancel = std.atomic.Value(bool){ .raw = false };
    const State = struct {};
    var st = State{};
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var ctx = Ctx(State){ .arena = arena.allocator(), .state = &st, .id = 9, .cancel = &cancel, .emit = &h.sink };
    const ch = ctx.channel(struct { pct: u8 });
    ch.send(.{ .pct = 42 });
    try std.testing.expect(std.mem.indexOf(u8, h.log.items, "window.Zigware._stream(9, ") != null);
    try std.testing.expect(std.mem.indexOf(u8, h.log.items, "\"pct\":42") != null);
}

test "Channel.close emits _streamEnd" {
    const h = Holder.make(std.testing.allocator);
    defer h.deinit();
    var cancel = std.atomic.Value(bool){ .raw = false };
    const State = struct {};
    var st = State{};
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var ctx = Ctx(State){ .arena = arena.allocator(), .state = &st, .id = 9, .cancel = &cancel, .emit = &h.sink };
    ctx.channel(struct {}).close();
    try std.testing.expect(std.mem.indexOf(u8, h.log.items, "window.Zigware._streamEnd(9);") != null);
}

test "cancelled reads the cancel token" {
    const h = Holder.make(std.testing.allocator);
    defer h.deinit();
    var cancel = std.atomic.Value(bool){ .raw = false };
    const State = struct {};
    var st = State{};
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var ctx = Ctx(State){ .arena = arena.allocator(), .state = &st, .id = 1, .cancel = &cancel, .emit = &h.sink };
    try std.testing.expect(!ctx.cancelled());
    cancel.store(true, .release);
    try std.testing.expect(ctx.cancelled());
}

test "done wraps a value in the Async marker" {
    const a = done(@as(i64, 5));
    try std.testing.expectEqual(@as(i64, 5), a.inner);
}

test "binaryChunk parks bytes and emits a _bin control frame" {
    const h = Holder.make(std.testing.allocator);
    defer h.deinit();
    var cancel = std.atomic.Value(bool){ .raw = false };
    const State = struct {};
    var st = State{};
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    var ctx = Ctx(State){ .arena = arena.allocator(), .state = &st, .id = 9, .cancel = &cancel, .emit = &h.sink };

    // First chunk: seq 0.
    const result = ctx.binaryChunk(&[_]u8{ 1, 2, 3, 4 }, "image/png");
    try std.testing.expect(result);
    try std.testing.expect(std.mem.indexOf(u8, h.log.items, &[_]u8{ 1, 2, 3, 4 }) != null);
    try std.testing.expect(std.mem.indexOf(u8, h.log.items, "window.Zigware._bin(9, 0, 4, ") != null);
    try std.testing.expect(std.mem.indexOf(u8, h.log.items, "image\\/png") != null);

    // Second chunk: seq advances to 1.
    _ = ctx.binaryChunk(&[_]u8{ 5, 6 }, "image/png");
    try std.testing.expect(std.mem.indexOf(u8, h.log.items, "window.Zigware._bin(9, 1, ") != null);
}
