// Vendored from Zigware; regenerated by `zigware init`. Do not hand-edit.
//
// Scaffold-local codegen entry point. `zig build dts` runs this to regenerate
// frontend/bindings.d.ts from the project's own command module.
const std = @import("std");
const emit_dts = @import("emit_dts.zig");
const app = @import("src/commands/crypto.zig");

pub fn main() !void {
    var dbg: std.heap.DebugAllocator(.{}) = .init;
    defer _ = dbg.deinit();
    const gpa = dbg.allocator();

    var threaded = std.Io.Threaded.init(gpa, .{});
    defer threaded.deinit();
    const io = threaded.io();

    var aw = std.Io.Writer.Allocating.init(gpa);
    defer aw.deinit();
    try emit_dts.emit(&aw.writer, struct {}, app.Commands);

    var dir = std.Io.Dir.cwd();
    try dir.writeFile(io, .{ .sub_path = "frontend/bindings.d.ts", .data = aw.writer.buffered() });
}
