// Vendored from Zigware; regenerated by `zigware init`. Do not hand-edit.
//
// Base build script for a Zigware project. `zig build` links the app; `zig build
// dts` regenerates frontend/bindings.d.ts from src/commands. The `-Drelease=true`
// flag selects ReleaseSafe (Zigware never ships with bounds checks stripped).
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{ .preferred_optimize_mode = .ReleaseSafe });

    // The vendored framework surface (command context types plus the wire
    // protocol) exposed as a named `zigware` module. Rooted at the vendored
    // command_ctx.zig, whose `@import("protocol.zig")` resolves as a sibling at
    // the project root. Every module that touches the command types imports this
    // ONE instance, so the codegen's `== CommandError` type checks hold.
    const zigware_mod = b.createModule(.{
        .root_source_file = b.path("command_ctx.zig"),
        .target = target,
        .optimize = optimize,
    });

    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    exe_mod.linkFramework("Cocoa", .{});
    exe_mod.linkFramework("WebKit", .{});
    exe_mod.addImport("zigware", zigware_mod);
    // Frontend assets live outside src/, so expose them as anonymous imports that
    // @embedFile can reference by name.
    exe_mod.addAnonymousImport("frontend/index.html", .{ .root_source_file = b.path("frontend/index.html") });

    const exe = b.addExecutable(.{ .name = "crypto-vanilla", .root_module = exe_mod });
    b.installArtifact(exe);

    const run_cmd = b.addRunArtifact(exe);
    if (b.args) |args| run_cmd.addArgs(args);
    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);

    // dts codegen: a Cocoa/WebKit-free exe that walks src/commands and writes
    // frontend/bindings.d.ts. Rooted at the vendored bindgen.zig.
    const dts_mod = b.createModule(.{
        .root_source_file = b.path("bindgen.zig"),
        .target = target,
        .optimize = optimize,
    });
    dts_mod.addImport("zigware", zigware_mod);
    const dts_exe = b.addExecutable(.{ .name = "bindgen", .root_module = dts_mod });
    const dts_run = b.addRunArtifact(dts_exe);
    const dts_step = b.step("dts", "Generate frontend/bindings.d.ts");
    dts_step.dependOn(&dts_run.step);

    // Tests over the command module.
    const test_mod = b.createModule(.{
        .root_source_file = b.path("src/commands/crypto.zig"),
        .target = target,
        .optimize = optimize,
    });
    test_mod.addImport("zigware", zigware_mod);
    const unit_tests = b.addTest(.{ .root_module = test_mod });
    const test_step = b.step("test", "Run tests");
    test_step.dependOn(&b.addRunArtifact(unit_tests).step);
}
