const std = @import("std");
const registry = @import("registry.zig");
const ctxmod = @import("command_ctx.zig");
const NullBackend = @import("platform/null.zig").NullBackend;
const builtin = @import("commands/builtin.zig");

const Async = ctxmod.Async;
const Bytes = ctxmod.Bytes;
const CommandError = ctxmod.CommandError;

/// Map a Zig type to a TS type string. An unmappable type (pointer, opaque) is a
/// comptime error naming the field, so an un-typeable surface fails the build.
fn tsType(comptime T: type) []const u8 {
    if (T == Bytes) return "Uint8Array";
    if (T == []const u8) return "string";
    return switch (@typeInfo(T)) {
        .bool => "boolean",
        .int => "number",
        .comptime_int => "number",
        .float => "number",
        .optional => |o| tsType(o.child) ++ " | null",
        .@"enum" => |e| comptime blk: {
            var s: []const u8 = "";
            for (e.fields, 0..) |f, i| {
                s = s ++ (if (i == 0) "" else " | ") ++ "\"" ++ f.name ++ "\"";
            }
            break :blk s;
        },
        .@"struct" => |st| comptime blk: {
            var s: []const u8 = "{ ";
            for (st.fields, 0..) |f, i| {
                s = s ++ (if (i == 0) "" else "; ") ++ f.name ++ ": " ++ tsType(f.type);
            }
            break :blk s ++ " }";
        },
        .pointer => @compileError("cannot map pointer type " ++ @typeName(T) ++ " to TS"),
        else => @compileError("cannot map type " ++ @typeName(T) ++ " to TS"),
    };
}

/// Unwrap Async, then unwrap Result to its ok leaf (the failure path is the
/// thrown ZigError, not part of the success type).
fn resultLeaf(comptime Ret: type) type {
    var T = Ret;
    // Async(X) -> X
    const ai = @typeInfo(T);
    if (ai == .@"struct" and ai.@"struct".fields.len == 1 and std.mem.eql(u8, ai.@"struct".fields[0].name, "inner")) {
        T = ai.@"struct".fields[0].type;
    }
    // Result(X) -> X (union(enum){ ok: X, err: CommandError })
    const ri = @typeInfo(T);
    if (ri == .@"union" and ri.@"union".fields.len == 2 and ri.@"union".fields[1].type == CommandError) {
        return ri.@"union".fields[0].type;
    }
    return T;
}

fn emit(w: *std.Io.Writer, comptime State: type, comptime UserCommands: type) !void {
    try w.writeAll("// Generated by `zig build dts`. Do not edit by hand.\n");
    try w.writeAll("// u64/i64 may exceed Number.MAX_SAFE_INTEGER.\n\n");
    try w.writeAll("export interface ZigCommands {\n");

    inline for (@typeInfo(UserCommands).@"struct".decls) |d| {
        const f = @field(UserCommands, d.name);
        if (@typeInfo(@TypeOf(f)) != .@"fn") continue;
        const fn_info = @typeInfo(@TypeOf(f)).@"fn";

        const ArgsTs = if (fn_info.params.len == 2) tsType(fn_info.params[1].type.?) else "{}";
        const ResultTs = tsType(resultLeaf(fn_info.return_type.?));

        try w.print("  {s}: {{ args: {s}; result: {s}; stream: unknown }};\n", .{ d.name, ArgsTs, ResultTs });
    }

    try w.writeAll("}\n\n");
    try w.writeAll(
        \\export declare namespace Zigware {
        \\  function invoke<C extends keyof ZigCommands>(
        \\    name: C, args: ZigCommands[C]["args"],
        \\    opts?: { onStream?: (frame: ZigCommands[C]["stream"]) => void }
        \\  ): Promise<ZigCommands[C]["result"]>;
        \\}
        \\
    );
    _ = State;
}

pub fn main() !void {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    var aw: std.Io.Writer.Allocating = .init(alloc);
    defer aw.deinit();

    // emit_dts walks the built-in Commands for v0.1.0; sub-project H wires the
    // app's own Commands. This file is the contract the frontend type-checks.
    try emit(&aw.writer, builtin.State, builtin.Commands);

    // 0.16 filesystem API: std.Io.Dir.cwd() + io-taking writeFile
    // (std.fs.cwd() does not exist on this toolchain).
    var threaded = std.Io.Threaded.init(alloc, .{});
    defer threaded.deinit();
    const io = threaded.io();
    try std.Io.Dir.cwd().writeFile(io, .{
        .sub_path = "frontend/bindings.d.ts",
        .data = aw.writer.buffered(),
    });
}

comptime {
    // Keep the spec-mandated imports referenced so emit_dts can instantiate
    // Commands(NullBackend, State, UserCommands) without an unused-import error.
    _ = registry;
    _ = NullBackend;
}
