const std = @import("std");
const ctxmod = @import("command_ctx.zig");
const builtin = @import("commands/builtin.zig");
const compute = @import("compute.zig");

const Async = ctxmod.Async;
const Bytes = ctxmod.Bytes;
const CommandError = ctxmod.CommandError;

/// Map a Zig type to a TS type string. An unmappable type (pointer, opaque) is a
/// comptime error naming the field, so an un-typeable surface fails the build.
fn tsType(comptime T: type) []const u8 {
    if (T == Bytes) return "Uint8Array";
    if (T == []const u8) return "string";
    return switch (@typeInfo(T)) {
        .bool => "boolean",
        .int => "number",
        .comptime_int => "number",
        .float => "number",
        .optional => |o| tsType(o.child) ++ " | null",
        .@"enum" => |e| comptime blk: {
            var s: []const u8 = "";
            for (e.fields, 0..) |f, i| {
                s = s ++ (if (i == 0) "" else " | ") ++ "\"" ++ f.name ++ "\"";
            }
            break :blk s;
        },
        .@"struct" => |st| comptime blk: {
            var s: []const u8 = "{ ";
            for (st.fields, 0..) |f, i| {
                s = s ++ (if (i == 0) "" else "; ") ++ f.name ++ ": " ++ tsType(f.type);
            }
            break :blk s ++ " }";
        },
        .pointer => @compileError("cannot map pointer type " ++ @typeName(T) ++ " to TS"),
        else => @compileError("cannot map type " ++ @typeName(T) ++ " to TS"),
    };
}

/// Unwrap Async, then unwrap Result to its ok leaf (the failure path is the
/// thrown ZigError, not part of the success type).
fn resultLeaf(comptime Ret: type) type {
    var T = Ret;
    // Async(X) -> X
    const ai = @typeInfo(T);
    if (ai == .@"struct" and ai.@"struct".fields.len == 1 and std.mem.eql(u8, ai.@"struct".fields[0].name, "inner")) {
        T = ai.@"struct".fields[0].type;
    }
    // Result(X) -> X (union(enum){ ok: X, err: CommandError })
    const ri = @typeInfo(T);
    if (ri == .@"union" and ri.@"union".fields.len == 2 and ri.@"union".fields[1].type == CommandError) {
        return ri.@"union".fields[0].type;
    }
    return T;
}

/// Recover the progress payload `P` from a streaming handler's third parameter.
/// By convention that parameter is `compute.Sink(P)` (registry.validate enforces
/// it). `Sink(P)` stores no P-typed field but exposes `progress(self, v: P)`, so
/// read P off that method's second parameter. Parallels resultLeaf's unwrap.
fn streamLeaf(comptime SinkT: type) type {
    return @typeInfo(@TypeOf(SinkT.progress)).@"fn".params[1].type.?;
}

pub fn emit(w: *std.Io.Writer, comptime State: type, comptime UserCommands: type) !void {
    try w.writeAll("// Generated by `zig build dts`. Do not edit by hand.\n");
    try w.writeAll("// u64/i64 may exceed Number.MAX_SAFE_INTEGER.\n\n");
    try w.writeAll("export interface ZigCommands {\n");

    inline for (@typeInfo(UserCommands).@"struct".decls) |d| {
        const f = @field(UserCommands, d.name);
        if (@typeInfo(@TypeOf(f)) != .@"fn") continue;
        const fn_info = @typeInfo(@TypeOf(f)).@"fn";

        const ArgsTs = if (fn_info.params.len >= 2) tsType(fn_info.params[1].type.?) else "{}";
        const ResultTs = tsType(resultLeaf(fn_info.return_type.?));
        // A streaming command lifts its progress payload P into an explicit third
        // param `sink: z.Sink(P)`; emit the real TS for P. A command with no such
        // param cannot stream, so its frame type is the known-absent `never`.
        const StreamTs = if (fn_info.params.len == 3) tsType(streamLeaf(fn_info.params[2].type.?)) else "never";

        try w.print("  {s}: {{ args: {s}; result: {s}; stream: {s} }};\n", .{ d.name, ArgsTs, ResultTs, StreamTs });
    }

    try w.writeAll("}\n\n");
    try w.writeAll(
        \\export declare namespace Zigware {
        \\  function invoke<C extends keyof ZigCommands>(
        \\    name: C, args: ZigCommands[C]["args"],
        \\    opts?: { onStream?: (frame: ZigCommands[C]["stream"]) => void }
        \\  ): Promise<ZigCommands[C]["result"]>;
        \\}
        \\
    );
    _ = State;
}

pub fn main() !void {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    var aw: std.Io.Writer.Allocating = .init(alloc);
    defer aw.deinit();

    // emit_dts walks the built-in Commands for v0.1.0; sub-project H wires the
    // app's own Commands. This file is the contract the frontend type-checks.
    try emit(&aw.writer, builtin.State, builtin.Commands);

    // 0.16 filesystem API: std.Io.Dir.cwd() + io-taking writeFile
    // (std.fs.cwd() does not exist on this toolchain).
    var threaded = std.Io.Threaded.init(alloc, .{});
    defer threaded.deinit();
    const io = threaded.io();
    try std.Io.Dir.cwd().writeFile(io, .{
        .sub_path = "frontend/bindings.d.ts",
        .data = aw.writer.buffered(),
    });
}

// --- Tests ---

const TestState = struct {};

/// Exercises both emit paths: `track` streams a NESTED progress struct (so the
/// stream path drives tsType's struct recursion), and `ping` cannot stream (so
/// it must render the known-absent `never`).
const EmitFixture = struct {
    const Stage = struct { stage: []const u8, progress: struct { done: u32, total: u32 } };
    pub fn track(_: *ctxmod.Ctx(TestState), _: struct { id: u64 }, _: compute.Sink(Stage)) ctxmod.Async(ctxmod.Result(struct { ok: bool })) {
        return ctxmod.done(ctxmod.Result(struct { ok: bool }){ .ok = .{ .ok = true } });
    }
    pub fn ping(_: *ctxmod.Ctx(TestState), _: struct { id: u64 }) ctxmod.Result(struct { ok: bool }) {
        return .{ .ok = .{ .ok = true } };
    }
};

test "streaming command emits the real nested stream payload type" {
    var aw: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer aw.deinit();
    try emit(&aw.writer, TestState, EmitFixture);
    const out = aw.writer.buffered();
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "stream: { stage: string; progress: { done: number; total: number } }",
    ) != null);
}

test "non-streaming command emits a never stream type" {
    var aw: std.Io.Writer.Allocating = .init(std.testing.allocator);
    defer aw.deinit();
    try emit(&aw.writer, TestState, EmitFixture);
    const out = aw.writer.buffered();
    try std.testing.expect(std.mem.indexOf(
        u8,
        out,
        "ping: { args: { id: number }; result: { ok: boolean }; stream: never }",
    ) != null);
}
